// Package countries is the country reference data for help.getCountriesList.
//
// Generated file: server/scripts/generate-countries.py
// Sources: the phonenumbers library (codes and number lengths) and pycountry (names).
package countries

// Country is a country in the shape the client expects on the sign-in screen.
type Country struct {
	ISO2        string   // country code, for example RS
	NameEN      string   // name in English
	NameRU      string   // name in Russian
	CountryCode string   // phone code without the plus, for example 381
	Patterns    []string // number patterns: X stands for any digit
}

// All holds every country, sorted by the English name.
var All = []Country{
	{ISO2: "AF", NameEN: "Afghanistan", NameRU: "Афганистан", CountryCode: "93", Patterns: []string{"XXXXXXXXX"}},
	{ISO2: "AL", NameEN: "Albania", NameRU: "Албания", CountryCode: "355", Patterns: []string{"XXXXXXXXX"}},
	{ISO2: "DZ", NameEN: "Algeria", NameRU: "Алжир", CountryCode: "213", Patterns: []string{"XXXXXXXXX"}},
	{ISO2: "AS", NameEN: "American Samoa", NameRU: "Американские Самоа", CountryCode: "1", Patterns: []string{"XXXXXXXXXX"}},
	{ISO2: "AD", NameEN: "Andorra", NameRU: "Андорра", CountryCode: "376", Patterns: []string{"XXXXXX", "XXXXXXXXX"}},
	{ISO2: "AO", NameEN: "Angola", NameRU: "Ангола", CountryCode: "244", Patterns: []string{"XXXXXXXXX"}},
	{ISO2: "AI", NameEN: "Anguilla", NameRU: "Ангвилла", CountryCode: "1", Patterns: []string{"XXXXXXXXXX"}},
	{ISO2: "AG", NameEN: "Antigua and Barbuda", NameRU: "Антигуа и Барбуда", CountryCode: "1", Patterns: []string{"XXXXXXXXXX"}},
	{ISO2: "AR", NameEN: "Argentina", NameRU: "Аргентина", CountryCode: "54", Patterns: []string{"XXXXXXXXXX", "XXXXXXXXXXX"}},
	{ISO2: "AM", NameEN: "Armenia", NameRU: "Армения", CountryCode: "374", Patterns: []string{"XXXXXXXX"}},
	{ISO2: "AW", NameEN: "Aruba", NameRU: "Аруба", CountryCode: "297", Patterns: []string{"XXXXXXX"}},
	{ISO2: "AU", NameEN: "Australia", NameRU: "Австралия", CountryCode: "61", Patterns: []string{"XXXXXXXXX"}},
	{ISO2: "AT", NameEN: "Austria", NameRU: "Австрия", CountryCode: "43", Patterns: []string{"XXXXXXX", "XXXXXXXX", "XXXXXXXXX", "XXXXXXXXXX", "XXXXXXXXXXX", "XXXXXXXXXXXX", "XXXXXXXXXXXXX"}},
	{ISO2: "AZ", NameEN: "Azerbaijan", NameRU: "Азербайджан", CountryCode: "994", Patterns: []string{"XXXXXXXXX"}},
	{ISO2: "BS", NameEN: "Bahamas", NameRU: "Багамы", CountryCode: "1", Patterns: []string{"XXXXXXXXXX"}},
	{ISO2: "BH", NameEN: "Bahrain", NameRU: "Бахрейн", CountryCode: "973", Patterns: []string{"XXXXXXXX"}},
	{ISO2: "BD", NameEN: "Bangladesh", NameRU: "Бангладеш", CountryCode: "880", Patterns: []string{"XXXXXXXXXX"}},
	{ISO2: "BB", NameEN: "Barbados", NameRU: "Барбадос", CountryCode: "1", Patterns: []string{"XXXXXXXXXX"}},
	{ISO2: "BY", NameEN: "Belarus", NameRU: "Беларусь", CountryCode: "375", Patterns: []string{"XXXXXXXXX"}},
	{ISO2: "BE", NameEN: "Belgium", NameRU: "Бельгия", CountryCode: "32", Patterns: []string{"XXXXXXXXX"}},
	{ISO2: "BZ", NameEN: "Belize", NameRU: "Белиз", CountryCode: "501", Patterns: []string{"XXXXXXX"}},
	{ISO2: "BJ", NameEN: "Benin", NameRU: "Бенин", CountryCode: "229", Patterns: []string{"XXXXXXXXXX"}},
	{ISO2: "BM", NameEN: "Bermuda", NameRU: "Бермуды", CountryCode: "1", Patterns: []string{"XXXXXXXXXX"}},
	{ISO2: "BT", NameEN: "Bhutan", NameRU: "Бутан", CountryCode: "975", Patterns: []string{"XXXXXXXX"}},
	{ISO2: "BO", NameEN: "Bolivia", NameRU: "Боливия", CountryCode: "591", Patterns: []string{"XXXXXXXX"}},
	{ISO2: "BQ", NameEN: "Bonaire, Sint Eustatius and Saba", NameRU: "Бонайре, Синт-Эстатиус и Саба", CountryCode: "599", Patterns: []string{"XXXXXXX"}},
	{ISO2: "BA", NameEN: "Bosnia and Herzegovina", NameRU: "Босния и Герцеговина", CountryCode: "387", Patterns: []string{"XXXXXXXX", "XXXXXXXXX"}},
	{ISO2: "BW", NameEN: "Botswana", NameRU: "Ботсвана", CountryCode: "267", Patterns: []string{"XXXXXXXX"}},
	{ISO2: "BR", NameEN: "Brazil", NameRU: "Бразилия", CountryCode: "55", Patterns: []string{"XXXXXXXXXX", "XXXXXXXXXXX"}},
	{ISO2: "IO", NameEN: "British Indian Ocean Territory", NameRU: "Британская территория Индийского океана", CountryCode: "246", Patterns: []string{"XXXXXXX"}},
	{ISO2: "BN", NameEN: "Brunei Darussalam", NameRU: "Бруней Даруссалам", CountryCode: "673", Patterns: []string{"XXXXXXX"}},
	{ISO2: "BG", NameEN: "Bulgaria", NameRU: "Болгария", CountryCode: "359", Patterns: []string{"XXXXXXXX", "XXXXXXXXX"}},
	{ISO2: "BF", NameEN: "Burkina Faso", NameRU: "Буркина-Фасо", CountryCode: "226", Patterns: []string{"XXXXXXXX"}},
	{ISO2: "BI", NameEN: "Burundi", NameRU: "Бурунди", CountryCode: "257", Patterns: []string{"XXXXXXXX"}},
	{ISO2: "CV", NameEN: "Cabo Verde", NameRU: "Кабо-Верде", CountryCode: "238", Patterns: []string{"XXXXXXX"}},
	{ISO2: "KH", NameEN: "Cambodia", NameRU: "Камбоджа", CountryCode: "855", Patterns: []string{"XXXXXXXX", "XXXXXXXXX"}},
	{ISO2: "CM", NameEN: "Cameroon", NameRU: "Камерун", CountryCode: "237", Patterns: []string{"XXXXXXXXX"}},
	{ISO2: "CA", NameEN: "Canada", NameRU: "Канада", CountryCode: "1", Patterns: []string{"XXXXXXXXXX"}},
	{ISO2: "KY", NameEN: "Cayman Islands", NameRU: "Каймановы острова", CountryCode: "1", Patterns: []string{"XXXXXXXXXX"}},
	{ISO2: "CF", NameEN: "Central African Republic", NameRU: "Центрально-африканская республика", CountryCode: "236", Patterns: []string{"XXXXXXXX"}},
	{ISO2: "TD", NameEN: "Chad", NameRU: "Чад", CountryCode: "235", Patterns: []string{"XXXXXXXX"}},
	{ISO2: "CL", NameEN: "Chile", NameRU: "Чили", CountryCode: "56", Patterns: []string{"XXXXXXXXX"}},
	{ISO2: "CN", NameEN: "China", NameRU: "Китай", CountryCode: "86", Patterns: []string{"XXXXXXXXXXX"}},
	{ISO2: "CX", NameEN: "Christmas Island", NameRU: "Остров Рождества", CountryCode: "61", Patterns: []string{"XXXXXXXXX"}},
	{ISO2: "CC", NameEN: "Cocos (Keeling) Islands", NameRU: "Кокосовые острова", CountryCode: "61", Patterns: []string{"XXXXXXXXX"}},
	{ISO2: "CO", NameEN: "Colombia", NameRU: "Колумбия", CountryCode: "57", Patterns: []string{"XXXXXXXXXX"}},
	{ISO2: "KM", NameEN: "Comoros", NameRU: "Коморы", CountryCode: "269", Patterns: []string{"XXXXXXX"}},
	{ISO2: "CG", NameEN: "Congo", NameRU: "Конго", CountryCode: "242", Patterns: []string{"XXXXXXXXX"}},
	{ISO2: "CD", NameEN: "Congo, The Democratic Republic of the", NameRU: "Демократическая Республика Конго", CountryCode: "243", Patterns: []string{"XXXXXXX", "XXXXXXXXX"}},
	{ISO2: "CK", NameEN: "Cook Islands", NameRU: "Острова Кука", CountryCode: "682", Patterns: []string{"XXXXX"}},
	{ISO2: "CR", NameEN: "Costa Rica", NameRU: "Коста-Рика", CountryCode: "506", Patterns: []string{"XXXXXXXX"}},
	{ISO2: "HR", NameEN: "Croatia", NameRU: "Хорватия", CountryCode: "385", Patterns: []string{"XXXXXXXX", "XXXXXXXXX"}},
	{ISO2: "CU", NameEN: "Cuba", NameRU: "Куба", CountryCode: "53", Patterns: []string{"XXXXXXXX"}},
	{ISO2: "CW", NameEN: "Cura\u00e7ao", NameRU: "Кюрасао", CountryCode: "599", Patterns: []string{"XXXXXXX", "XXXXXXXX"}},
	{ISO2: "CY", NameEN: "Cyprus", NameRU: "Кипр", CountryCode: "357", Patterns: []string{"XXXXXXXX"}},
	{ISO2: "CZ", NameEN: "Czechia", NameRU: "Чехия", CountryCode: "420", Patterns: []string{"XXXXXXXXX"}},
	{ISO2: "CI", NameEN: "C\u00f4te d'Ivoire", NameRU: "Кот-д'Ивуар", CountryCode: "225", Patterns: []string{"XXXXXXXXXX"}},
	{ISO2: "DK", NameEN: "Denmark", NameRU: "Дания", CountryCode: "45", Patterns: []string{"XXXXXXXX"}},
	{ISO2: "DJ", NameEN: "Djibouti", NameRU: "Джибути", CountryCode: "253", Patterns: []string{"XXXXXXXX"}},
	{ISO2: "DM", NameEN: "Dominica", NameRU: "Доминика", CountryCode: "1", Patterns: []string{"XXXXXXXXXX"}},
	{ISO2: "DO", NameEN: "Dominican Republic", NameRU: "Доминиканская республика", CountryCode: "1", Patterns: []string{"XXXXXXXXXX"}},
	{ISO2: "EC", NameEN: "Ecuador", NameRU: "Эквадор", CountryCode: "593", Patterns: []string{"XXXXXXXXX"}},
	{ISO2: "EG", NameEN: "Egypt", NameRU: "Египет", CountryCode: "20", Patterns: []string{"XXXXXXXXXX"}},
	{ISO2: "SV", NameEN: "El Salvador", NameRU: "Сальвадор", CountryCode: "503", Patterns: []string{"XXXXXXXX"}},
	{ISO2: "GQ", NameEN: "Equatorial Guinea", NameRU: "Экваториальная Гвинея", CountryCode: "240", Patterns: []string{"XXXXXXXXX"}},
	{ISO2: "ER", NameEN: "Eritrea", NameRU: "Эритрея", CountryCode: "291", Patterns: []string{"XXXXXXX"}},
	{ISO2: "EE", NameEN: "Estonia", NameRU: "Эстония", CountryCode: "372", Patterns: []string{"XXXXXXX", "XXXXXXXX"}},
	{ISO2: "SZ", NameEN: "Eswatini", NameRU: "Эсватини", CountryCode: "268", Patterns: []string{"XXXXXXXX"}},
	{ISO2: "ET", NameEN: "Ethiopia", NameRU: "Эфиопия", CountryCode: "251", Patterns: []string{"XXXXXXXXX"}},
	{ISO2: "FK", NameEN: "Falkland Islands (Malvinas)", NameRU: "Фолклендские (Мальвинские) острова", CountryCode: "500", Patterns: []string{"XXXXX"}},
	{ISO2: "FO", NameEN: "Faroe Islands", NameRU: "Фарерские острова", CountryCode: "298", Patterns: []string{"XXXXXX"}},
	{ISO2: "FJ", NameEN: "Fiji", NameRU: "Фиджи", CountryCode: "679", Patterns: []string{"XXXXXXX"}},
	{ISO2: "FI", NameEN: "Finland", NameRU: "Финляндия", CountryCode: "358", Patterns: []string{"XXXXXX", "XXXXXXX", "XXXXXXXX", "XXXXXXXXX", "XXXXXXXXXX"}},
	{ISO2: "FR", NameEN: "France", NameRU: "Франция", CountryCode: "33", Patterns: []string{"XXXXXXXXX"}},
	{ISO2: "GF", NameEN: "French Guiana", NameRU: "Французская Гвиана", CountryCode: "594", Patterns: []string{"XXXXXXXXX"}},
	{ISO2: "PF", NameEN: "French Polynesia", NameRU: "Французская Полинезия", CountryCode: "689", Patterns: []string{"XXXXXXXX"}},
	{ISO2: "GA", NameEN: "Gabon", NameRU: "Габон", CountryCode: "241", Patterns: []string{"XXXXXXX", "XXXXXXXX"}},
	{ISO2: "GM", NameEN: "Gambia", NameRU: "Гамбия", CountryCode: "220", Patterns: []string{"XXXXXXX"}},
	{ISO2: "GE", NameEN: "Georgia", NameRU: "Грузия", CountryCode: "995", Patterns: []string{"XXXXXXXXX"}},
	{ISO2: "DE", NameEN: "Germany", NameRU: "Германия", CountryCode: "49", Patterns: []string{"XXXXXXXXXX", "XXXXXXXXXXX"}},
	{ISO2: "GH", NameEN: "Ghana", NameRU: "Гана", CountryCode: "233", Patterns: []string{"XXXXXXXXX"}},
	{ISO2: "GI", NameEN: "Gibraltar", NameRU: "Гибралтар", CountryCode: "350", Patterns: []string{"XXXXXXXX"}},
	{ISO2: "GR", NameEN: "Greece", NameRU: "Греция", CountryCode: "30", Patterns: []string{"XXXXXXXXXX"}},
	{ISO2: "GL", NameEN: "Greenland", NameRU: "Гренландия", CountryCode: "299", Patterns: []string{"XXXXXX"}},
	{ISO2: "GD", NameEN: "Grenada", NameRU: "Гренада", CountryCode: "1", Patterns: []string{"XXXXXXXXXX"}},
	{ISO2: "GP", NameEN: "Guadeloupe", NameRU: "Гваделупа", CountryCode: "590", Patterns: []string{"XXXXXXXXX"}},
	{ISO2: "GU", NameEN: "Guam", NameRU: "Гуам", CountryCode: "1", Patterns: []string{"XXXXXXXXXX"}},
	{ISO2: "GT", NameEN: "Guatemala", NameRU: "Гватемала", CountryCode: "502", Patterns: []string{"XXXXXXXX"}},
	{ISO2: "GG", NameEN: "Guernsey", NameRU: "Гернси", CountryCode: "44", Patterns: []string{"XXXXXXXXXX"}},
	{ISO2: "GN", NameEN: "Guinea", NameRU: "Гвинея", CountryCode: "224", Patterns: []string{"XXXXXXXXX"}},
	{ISO2: "GW", NameEN: "Guinea-Bissau", NameRU: "Гвинея-Бисау", CountryCode: "245", Patterns: []string{"XXXXXXXXX"}},
	{ISO2: "GY", NameEN: "Guyana", NameRU: "Гайана", CountryCode: "592", Patterns: []string{"XXXXXXX"}},
	{ISO2: "HT", NameEN: "Haiti", NameRU: "Гаити", CountryCode: "509", Patterns: []string{"XXXXXXXX"}},
	{ISO2: "VA", NameEN: "Holy See (Vatican City State)", NameRU: "Государство-город Ватикан", CountryCode: "39", Patterns: []string{"XXXXXXXXX", "XXXXXXXXXX"}},
	{ISO2: "HN", NameEN: "Honduras", NameRU: "Гондурас", CountryCode: "504", Patterns: []string{"XXXXXXXX"}},
	{ISO2: "HK", NameEN: "Hong Kong", NameRU: "Гонконг", CountryCode: "852", Patterns: []string{"XXXXXXXX"}},
	{ISO2: "HU", NameEN: "Hungary", NameRU: "Венгрия", CountryCode: "36", Patterns: []string{"XXXXXXXXX"}},
	{ISO2: "IS", NameEN: "Iceland", NameRU: "Исландия", CountryCode: "354", Patterns: []string{"XXXXXXX", "XXXXXXXXX"}},
	{ISO2: "IN", NameEN: "India", NameRU: "Индия", CountryCode: "91", Patterns: []string{"XXXXXXXXXX"}},
	{ISO2: "ID", NameEN: "Indonesia", NameRU: "Индонезия", CountryCode: "62", Patterns: []string{"XXXXXXXXX", "XXXXXXXXXX", "XXXXXXXXXXX", "XXXXXXXXXXXX"}},
	{ISO2: "IR", NameEN: "Iran", NameRU: "Иран", CountryCode: "98", Patterns: []string{"XXXXXXXXXX"}},
	{ISO2: "IQ", NameEN: "Iraq", NameRU: "Ирак", CountryCode: "964", Patterns: []string{"XXXXXXXXXX"}},
	{ISO2: "IE", NameEN: "Ireland", NameRU: "Ирландия", CountryCode: "353", Patterns: []string{"XXXXXXXXX"}},
	{ISO2: "IM", NameEN: "Isle of Man", NameRU: "Остров Мэн", CountryCode: "44", Patterns: []string{"XXXXXXXXXX"}},
	{ISO2: "IL", NameEN: "Israel", NameRU: "Израиль", CountryCode: "972", Patterns: []string{"XXXXXXXXX"}},
	{ISO2: "IT", NameEN: "Italy", NameRU: "Италия", CountryCode: "39", Patterns: []string{"XXXXXXXXX", "XXXXXXXXXX"}},
	{ISO2: "JM", NameEN: "Jamaica", NameRU: "Ямайка", CountryCode: "1", Patterns: []string{"XXXXXXXXXX"}},
	{ISO2: "JP", NameEN: "Japan", NameRU: "Япония", CountryCode: "81", Patterns: []string{"XXXXXXXXXX"}},
	{ISO2: "JE", NameEN: "Jersey", NameRU: "Джерси", CountryCode: "44", Patterns: []string{"XXXXXXXXXX"}},
	{ISO2: "JO", NameEN: "Jordan", NameRU: "Иордания", CountryCode: "962", Patterns: []string{"XXXXXXXXX"}},
	{ISO2: "KZ", NameEN: "Kazakhstan", NameRU: "Казахстан", CountryCode: "7", Patterns: []string{"XXXXXXXXXX"}},
	{ISO2: "KE", NameEN: "Kenya", NameRU: "Кения", CountryCode: "254", Patterns: []string{"XXXXXXXXX"}},
	{ISO2: "KI", NameEN: "Kiribati", NameRU: "Кирибати", CountryCode: "686", Patterns: []string{"XXXXXXXX"}},
	{ISO2: "KW", NameEN: "Kuwait", NameRU: "Кувейт", CountryCode: "965", Patterns: []string{"XXXXXXXX"}},
	{ISO2: "KG", NameEN: "Kyrgyzstan", NameRU: "Киргизия", CountryCode: "996", Patterns: []string{"XXXXXXXXX"}},
	{ISO2: "LA", NameEN: "Laos", NameRU: "Лаосская Народно-Демократическая Республика", CountryCode: "856", Patterns: []string{"XXXXXXXXX", "XXXXXXXXXX"}},
	{ISO2: "LV", NameEN: "Latvia", NameRU: "Латвия", CountryCode: "371", Patterns: []string{"XXXXXXXX"}},
	{ISO2: "LB", NameEN: "Lebanon", NameRU: "Ливан", CountryCode: "961", Patterns: []string{"XXXXXXX", "XXXXXXXX"}},
	{ISO2: "LS", NameEN: "Lesotho", NameRU: "Лесото", CountryCode: "266", Patterns: []string{"XXXXXXXX"}},
	{ISO2: "LR", NameEN: "Liberia", NameRU: "Либерия", CountryCode: "231", Patterns: []string{"XXXXXXX", "XXXXXXXXX"}},
	{ISO2: "LY", NameEN: "Libya", NameRU: "Ливия", CountryCode: "218", Patterns: []string{"XXXXXXXXX"}},
	{ISO2: "LI", NameEN: "Liechtenstein", NameRU: "Лихтенштейн", CountryCode: "423", Patterns: []string{"XXXXXXX", "XXXXXXXXX"}},
	{ISO2: "LT", NameEN: "Lithuania", NameRU: "Литва", CountryCode: "370", Patterns: []string{"XXXXXXXX"}},
	{ISO2: "LU", NameEN: "Luxembourg", NameRU: "Люксембург", CountryCode: "352", Patterns: []string{"XXXXXXXXX"}},
	{ISO2: "MO", NameEN: "Macao", NameRU: "Макао", CountryCode: "853", Patterns: []string{"XXXXXXXX"}},
	{ISO2: "MG", NameEN: "Madagascar", NameRU: "Мадагаскар", CountryCode: "261", Patterns: []string{"XXXXXXXXX"}},
	{ISO2: "MW", NameEN: "Malawi", NameRU: "Малави", CountryCode: "265", Patterns: []string{"XXXXXXXXX"}},
	{ISO2: "MY", NameEN: "Malaysia", NameRU: "Малайзия", CountryCode: "60", Patterns: []string{"XXXXXXXXX", "XXXXXXXXXX"}},
	{ISO2: "MV", NameEN: "Maldives", NameRU: "Мальдивы", CountryCode: "960", Patterns: []string{"XXXXXXX"}},
	{ISO2: "ML", NameEN: "Mali", NameRU: "Мали", CountryCode: "223", Patterns: []string{"XXXXXXXX"}},
	{ISO2: "MT", NameEN: "Malta", NameRU: "Мальта", CountryCode: "356", Patterns: []string{"XXXXXXXX"}},
	{ISO2: "MH", NameEN: "Marshall Islands", NameRU: "Маршалловы острова", CountryCode: "692", Patterns: []string{"XXXXXXX"}},
	{ISO2: "MQ", NameEN: "Martinique", NameRU: "Мартиника", CountryCode: "596", Patterns: []string{"XXXXXXXXX"}},
	{ISO2: "MR", NameEN: "Mauritania", NameRU: "Мавритания", CountryCode: "222", Patterns: []string{"XXXXXXXX"}},
	{ISO2: "MU", NameEN: "Mauritius", NameRU: "Маврикий", CountryCode: "230", Patterns: []string{"XXXXXXXX"}},
	{ISO2: "YT", NameEN: "Mayotte", NameRU: "Майот", CountryCode: "262", Patterns: []string{"XXXXXXXXX"}},
	{ISO2: "MX", NameEN: "Mexico", NameRU: "Мексика", CountryCode: "52", Patterns: []string{"XXXXXXXXXX"}},
	{ISO2: "FM", NameEN: "Micronesia, Federated States of", NameRU: "Федеративные Штаты Микронезии", CountryCode: "691", Patterns: []string{"XXXXXXX"}},
	{ISO2: "MD", NameEN: "Moldova", NameRU: "Республика Молдова", CountryCode: "373", Patterns: []string{"XXXXXXXX"}},
	{ISO2: "MC", NameEN: "Monaco", NameRU: "Монако", CountryCode: "377", Patterns: []string{"XXXXXXXX", "XXXXXXXXX"}},
	{ISO2: "MN", NameEN: "Mongolia", NameRU: "Монголия", CountryCode: "976", Patterns: []string{"XXXXXXXX"}},
	{ISO2: "ME", NameEN: "Montenegro", NameRU: "Черногория", CountryCode: "382", Patterns: []string{"XXXXXXXX"}},
	{ISO2: "MS", NameEN: "Montserrat", NameRU: "Монтсеррат", CountryCode: "1", Patterns: []string{"XXXXXXXXXX"}},
	{ISO2: "MA", NameEN: "Morocco", NameRU: "Марокко", CountryCode: "212", Patterns: []string{"XXXXXXXXX"}},
	{ISO2: "MZ", NameEN: "Mozambique", NameRU: "Мозамбик", CountryCode: "258", Patterns: []string{"XXXXXXXXX"}},
	{ISO2: "MM", NameEN: "Myanmar", NameRU: "Мьянма", CountryCode: "95", Patterns: []string{"XXXXXXX", "XXXXXXXX", "XXXXXXXXX", "XXXXXXXXXX"}},
	{ISO2: "NA", NameEN: "Namibia", NameRU: "Намибия", CountryCode: "264", Patterns: []string{"XXXXXXXXX"}},
	{ISO2: "NR", NameEN: "Nauru", NameRU: "Науру", CountryCode: "674", Patterns: []string{"XXXXXXX"}},
	{ISO2: "NP", NameEN: "Nepal", NameRU: "Непал", CountryCode: "977", Patterns: []string{"XXXXXXXXXX"}},
	{ISO2: "NL", NameEN: "Netherlands", NameRU: "Нидерланды", CountryCode: "31", Patterns: []string{"XXXXXXXXX", "XXXXXXXXXXX"}},
	{ISO2: "NC", NameEN: "New Caledonia", NameRU: "Новая Каледония", CountryCode: "687", Patterns: []string{"XXXXXX"}},
	{ISO2: "NZ", NameEN: "New Zealand", NameRU: "Новая Зеландия", CountryCode: "64", Patterns: []string{"XXXXXXXX", "XXXXXXXXX", "XXXXXXXXXX"}},
	{ISO2: "NI", NameEN: "Nicaragua", NameRU: "Никарагуа", CountryCode: "505", Patterns: []string{"XXXXXXXX"}},
	{ISO2: "NE", NameEN: "Niger", NameRU: "Нигер", CountryCode: "227", Patterns: []string{"XXXXXXXX"}},
	{ISO2: "NG", NameEN: "Nigeria", NameRU: "Нигерия", CountryCode: "234", Patterns: []string{"XXXXXXXXXX"}},
	{ISO2: "NU", NameEN: "Niue", NameRU: "Ниуэ", CountryCode: "683", Patterns: []string{"XXXX", "XXXXXXX"}},
	{ISO2: "NF", NameEN: "Norfolk Island", NameRU: "Остров Норфолк", CountryCode: "672", Patterns: []string{"XXXXXX"}},
	{ISO2: "KP", NameEN: "North Korea", NameRU: "Корейская Народно-Демократическая Республика", CountryCode: "850", Patterns: []string{"XXXXXXXXXX"}},
	{ISO2: "MK", NameEN: "North Macedonia", NameRU: "Северная Македония", CountryCode: "389", Patterns: []string{"XXXXXXXX"}},
	{ISO2: "MP", NameEN: "Northern Mariana Islands", NameRU: "Острова северной Марианы", CountryCode: "1", Patterns: []string{"XXXXXXXXXX"}},
	{ISO2: "NO", NameEN: "Norway", NameRU: "Норвегия", CountryCode: "47", Patterns: []string{"XXXXXXXX"}},
	{ISO2: "OM", NameEN: "Oman", NameRU: "Оман", CountryCode: "968", Patterns: []string{"XXXXXXXX"}},
	{ISO2: "PK", NameEN: "Pakistan", NameRU: "Пакистан", CountryCode: "92", Patterns: []string{"XXXXXXXXXX"}},
	{ISO2: "PW", NameEN: "Palau", NameRU: "Палау", CountryCode: "680", Patterns: []string{"XXXXXXX"}},
	{ISO2: "PS", NameEN: "Palestine, State of", NameRU: "Палестина", CountryCode: "970", Patterns: []string{"XXXXXXXXX"}},
	{ISO2: "PA", NameEN: "Panama", NameRU: "Панама", CountryCode: "507", Patterns: []string{"XXXXXXX", "XXXXXXXX"}},
	{ISO2: "PG", NameEN: "Papua New Guinea", NameRU: "Папуа — Новая Гвинея", CountryCode: "675", Patterns: []string{"XXXXXXXX"}},
	{ISO2: "PY", NameEN: "Paraguay", NameRU: "Парагвай", CountryCode: "595", Patterns: []string{"XXXXXXXXX"}},
	{ISO2: "PE", NameEN: "Peru", NameRU: "Перу", CountryCode: "51", Patterns: []string{"XXXXXXXXX"}},
	{ISO2: "PH", NameEN: "Philippines", NameRU: "Филиппины", CountryCode: "63", Patterns: []string{"XXXXXXXXXX"}},
	{ISO2: "PL", NameEN: "Poland", NameRU: "Польша", CountryCode: "48", Patterns: []string{"XXXXXXXXX"}},
	{ISO2: "PT", NameEN: "Portugal", NameRU: "Португалия", CountryCode: "351", Patterns: []string{"XXXXXXXXX"}},
	{ISO2: "PR", NameEN: "Puerto Rico", NameRU: "Пуэрто-Рико", CountryCode: "1", Patterns: []string{"XXXXXXXXXX"}},
	{ISO2: "QA", NameEN: "Qatar", NameRU: "Катар", CountryCode: "974", Patterns: []string{"XXXXXXXX"}},
	{ISO2: "RO", NameEN: "Romania", NameRU: "Румыния", CountryCode: "40", Patterns: []string{"XXXXXXXXX"}},
	{ISO2: "RU", NameEN: "Russian Federation", NameRU: "Российская Федерация", CountryCode: "7", Patterns: []string{"XXXXXXXXXX"}},
	{ISO2: "RW", NameEN: "Rwanda", NameRU: "Руанда", CountryCode: "250", Patterns: []string{"XXXXXXXXX"}},
	{ISO2: "RE", NameEN: "R\u00e9union", NameRU: "Реюньон", CountryCode: "262", Patterns: []string{"XXXXXXXXX"}},
	{ISO2: "BL", NameEN: "Saint Barth\u00e9lemy", NameRU: "Сен-Бартельми", CountryCode: "590", Patterns: []string{"XXXXXXXXX"}},
	{ISO2: "SH", NameEN: "Saint Helena, Ascension and Tristan da Cunha", NameRU: "Остров Святой Елены, Остров Вознесения и Тристан-да-Кунья", CountryCode: "290", Patterns: []string{"XXXXX"}},
	{ISO2: "KN", NameEN: "Saint Kitts and Nevis", NameRU: "Сент-Китс и Невис", CountryCode: "1", Patterns: []string{"XXXXXXXXXX"}},
	{ISO2: "LC", NameEN: "Saint Lucia", NameRU: "Сент-Люсия", CountryCode: "1", Patterns: []string{"XXXXXXXXXX"}},
	{ISO2: "MF", NameEN: "Saint Martin (French part)", NameRU: "Сен-Мартен (Франция)", CountryCode: "590", Patterns: []string{"XXXXXXXXX"}},
	{ISO2: "PM", NameEN: "Saint Pierre and Miquelon", NameRU: "Сен-Пьер и Микелон", CountryCode: "508", Patterns: []string{"XXXXXX", "XXXXXXXXX"}},
	{ISO2: "VC", NameEN: "Saint Vincent and the Grenadines", NameRU: "Сент-Винсент и Гренадины", CountryCode: "1", Patterns: []string{"XXXXXXXXXX"}},
	{ISO2: "WS", NameEN: "Samoa", NameRU: "Самоа", CountryCode: "685", Patterns: []string{"XXXXXXX", "XXXXXXXXXX"}},
	{ISO2: "SM", NameEN: "San Marino", NameRU: "Сан-Марино", CountryCode: "378", Patterns: []string{"XXXXXXXX"}},
	{ISO2: "ST", NameEN: "Sao Tome and Principe", NameRU: "Сан-Томе и Принсипи", CountryCode: "239", Patterns: []string{"XXXXXXX"}},
	{ISO2: "SA", NameEN: "Saudi Arabia", NameRU: "Саудовская Аравия", CountryCode: "966", Patterns: []string{"XXXXXXXXX"}},
	{ISO2: "SN", NameEN: "Senegal", NameRU: "Сенегал", CountryCode: "221", Patterns: []string{"XXXXXXXXX"}},
	{ISO2: "RS", NameEN: "Serbia", NameRU: "Сербия", CountryCode: "381", Patterns: []string{"XXXXXXXX", "XXXXXXXXX", "XXXXXXXXXX"}},
	{ISO2: "SC", NameEN: "Seychelles", NameRU: "Сейшелы", CountryCode: "248", Patterns: []string{"XXXXXXX"}},
	{ISO2: "SL", NameEN: "Sierra Leone", NameRU: "Сьерра-Леоне", CountryCode: "232", Patterns: []string{"XXXXXXXX"}},
	{ISO2: "SG", NameEN: "Singapore", NameRU: "Сингапур", CountryCode: "65", Patterns: []string{"XXXXXXXX"}},
	{ISO2: "SX", NameEN: "Sint Maarten (Dutch part)", NameRU: "Синт-Мартен (голландская часть)", CountryCode: "1", Patterns: []string{"XXXXXXXXXX"}},
	{ISO2: "SK", NameEN: "Slovakia", NameRU: "Словакия", CountryCode: "421", Patterns: []string{"XXXXXXXXX"}},
	{ISO2: "SI", NameEN: "Slovenia", NameRU: "Словения", CountryCode: "386", Patterns: []string{"XXXXXXXX"}},
	{ISO2: "SB", NameEN: "Solomon Islands", NameRU: "Соломоновы Острова", CountryCode: "677", Patterns: []string{"XXXXX", "XXXXXXX"}},
	{ISO2: "SO", NameEN: "Somalia", NameRU: "Сомали", CountryCode: "252", Patterns: []string{"XXXXXXX", "XXXXXXXX", "XXXXXXXXX"}},
	{ISO2: "ZA", NameEN: "South Africa", NameRU: "Южная Африка", CountryCode: "27", Patterns: []string{"XXXXX", "XXXXXX", "XXXXXXX", "XXXXXXXX", "XXXXXXXXX"}},
	{ISO2: "KR", NameEN: "South Korea", NameRU: "Республика Корея", CountryCode: "82", Patterns: []string{"XXXXXXXXX", "XXXXXXXXXX"}},
	{ISO2: "SS", NameEN: "South Sudan", NameRU: "Южный Судан", CountryCode: "211", Patterns: []string{"XXXXXXXXX"}},
	{ISO2: "ES", NameEN: "Spain", NameRU: "Испания", CountryCode: "34", Patterns: []string{"XXXXXXXXX"}},
	{ISO2: "LK", NameEN: "Sri Lanka", NameRU: "Шри-Ланка", CountryCode: "94", Patterns: []string{"XXXXXXXXX"}},
	{ISO2: "SD", NameEN: "Sudan", NameRU: "Судан", CountryCode: "249", Patterns: []string{"XXXXXXXXX"}},
	{ISO2: "SR", NameEN: "Suriname", NameRU: "Суринам", CountryCode: "597", Patterns: []string{"XXXXXXX"}},
	{ISO2: "SJ", NameEN: "Svalbard and Jan Mayen", NameRU: "Шпицберген и Ян-Майен", CountryCode: "47", Patterns: []string{"XXXXXXXX"}},
	{ISO2: "SE", NameEN: "Sweden", NameRU: "Швеция", CountryCode: "46", Patterns: []string{"XXXXXXXXX"}},
	{ISO2: "CH", NameEN: "Switzerland", NameRU: "Швейцария", CountryCode: "41", Patterns: []string{"XXXXXXXXX"}},
	{ISO2: "SY", NameEN: "Syria", NameRU: "Сирийская Арабская Республика", CountryCode: "963", Patterns: []string{"XXXXXXXXX"}},
	{ISO2: "TW", NameEN: "Taiwan", NameRU: "Китайская провинция Тайвань", CountryCode: "886", Patterns: []string{"XXXXXXXXX"}},
	{ISO2: "TJ", NameEN: "Tajikistan", NameRU: "Таджикистан", CountryCode: "992", Patterns: []string{"XXXXXXXXX"}},
	{ISO2: "TZ", NameEN: "Tanzania", NameRU: "Танзания", CountryCode: "255", Patterns: []string{"XXXXXXXXX"}},
	{ISO2: "TH", NameEN: "Thailand", NameRU: "Таиланд", CountryCode: "66", Patterns: []string{"XXXXXXXXX"}},
	{ISO2: "TL", NameEN: "Timor-Leste", NameRU: "Восточный Тимор", CountryCode: "670", Patterns: []string{"XXXXXXXX"}},
	{ISO2: "TG", NameEN: "Togo", NameRU: "Того", CountryCode: "228", Patterns: []string{"XXXXXXXX"}},
	{ISO2: "TK", NameEN: "Tokelau", NameRU: "Токелау", CountryCode: "690", Patterns: []string{"XXXX", "XXXXX", "XXXXXX", "XXXXXXX"}},
	{ISO2: "TO", NameEN: "Tonga", NameRU: "Тонга", CountryCode: "676", Patterns: []string{"XXXXXXX"}},
	{ISO2: "TT", NameEN: "Trinidad and Tobago", NameRU: "Тринидад и Тобаго", CountryCode: "1", Patterns: []string{"XXXXXXXXXX"}},
	{ISO2: "TN", NameEN: "Tunisia", NameRU: "Тунис", CountryCode: "216", Patterns: []string{"XXXXXXXX"}},
	{ISO2: "TM", NameEN: "Turkmenistan", NameRU: "Туркменистан", CountryCode: "993", Patterns: []string{"XXXXXXXX"}},
	{ISO2: "TC", NameEN: "Turks and Caicos Islands", NameRU: "Острова Туркс и Каикос", CountryCode: "1", Patterns: []string{"XXXXXXXXXX"}},
	{ISO2: "TV", NameEN: "Tuvalu", NameRU: "Тувалу", CountryCode: "688", Patterns: []string{"XXXXXX", "XXXXXXX"}},
	{ISO2: "TR", NameEN: "T\u00fcrkiye", NameRU: "Türkiye", CountryCode: "90", Patterns: []string{"XXXXXXXXXX"}},
	{ISO2: "UG", NameEN: "Uganda", NameRU: "Уганда", CountryCode: "256", Patterns: []string{"XXXXXXXXX"}},
	{ISO2: "UA", NameEN: "Ukraine", NameRU: "Украина", CountryCode: "380", Patterns: []string{"XXXXXXXXX"}},
	{ISO2: "AE", NameEN: "United Arab Emirates", NameRU: "Объединённые Арабские Эмираты", CountryCode: "971", Patterns: []string{"XXXXXXXXX"}},
	{ISO2: "GB", NameEN: "United Kingdom", NameRU: "Соединённое Королевство", CountryCode: "44", Patterns: []string{"XXXXXXXXXX"}},
	{ISO2: "US", NameEN: "United States", NameRU: "Соединённые штаты", CountryCode: "1", Patterns: []string{"XXXXXXXXXX"}},
	{ISO2: "UY", NameEN: "Uruguay", NameRU: "Уругвай", CountryCode: "598", Patterns: []string{"XXXXXXXX"}},
	{ISO2: "UZ", NameEN: "Uzbekistan", NameRU: "Узбекистан", CountryCode: "998", Patterns: []string{"XXXXXXXXX"}},
	{ISO2: "VU", NameEN: "Vanuatu", NameRU: "Вануату", CountryCode: "678", Patterns: []string{"XXXXXXX"}},
	{ISO2: "VE", NameEN: "Venezuela", NameRU: "Боливарианская Республика Венесуэла", CountryCode: "58", Patterns: []string{"XXXXXXXXXX"}},
	{ISO2: "VN", NameEN: "Vietnam", NameRU: "Вьетнам", CountryCode: "84", Patterns: []string{"XXXXXXXXX"}},
	{ISO2: "VG", NameEN: "Virgin Islands, British", NameRU: "Виргинские острова (Британия)", CountryCode: "1", Patterns: []string{"XXXXXXXXXX"}},
	{ISO2: "VI", NameEN: "Virgin Islands, U.S.", NameRU: "Виргинские острова (США)", CountryCode: "1", Patterns: []string{"XXXXXXXXXX"}},
	{ISO2: "WF", NameEN: "Wallis and Futuna", NameRU: "Уоллес и Футана", CountryCode: "681", Patterns: []string{"XXXXXX"}},
	{ISO2: "EH", NameEN: "Western Sahara", NameRU: "Западная Сахара", CountryCode: "212", Patterns: []string{"XXXXXXXXX"}},
	{ISO2: "YE", NameEN: "Yemen", NameRU: "Йемен", CountryCode: "967", Patterns: []string{"XXXXXXXXX"}},
	{ISO2: "ZM", NameEN: "Zambia", NameRU: "Замбия", CountryCode: "260", Patterns: []string{"XXXXXXXXX"}},
	{ISO2: "ZW", NameEN: "Zimbabwe", NameRU: "Зимбабве", CountryCode: "263", Patterns: []string{"XXXXXXXXX"}},
	{ISO2: "AX", NameEN: "\u00c5land Islands", NameRU: "Аландские острова", CountryCode: "358", Patterns: []string{"XXXXXX", "XXXXXXX", "XXXXXXXX", "XXXXXXXXX", "XXXXXXXXXX"}},
}
